name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/debugger0/docker-http-python:$(date +%s)

    - name: Push the Docker image
      run: docker push docker.io/debugger0/docker-http-python:$(date +%s)